### ISSUE TITLE
Export PlantUML - Does not export method signature

### ISSUE THREAD

**Issue by arun-a-nayagam** [Vanco/SequencePlugin#118]
Hi,
By unchecking "Show simple call name", I am able to see the method signature in the generated sequence diagram.
![image](https://user-images.githubusercontent.com/25394330/159546460-39b8222f-6411-4e85-8202-c6477b4c91df.png)

But when I export PlantUML, the generated UML code does not contain the method signature.

Can you please change PlantUML export to generate the method signature as well, when "Show simple call name" is unchecked.

Appreciate your help on this.

**Comment by arun-a-nayagam** [comment]
Hi, 
I see that you have made some code changes to fix the issue, thank you so much for that.
But you have not changed the version of the plugin.
Can you please let me know, how to get those code changes to my local Intellij installation?

**Comment by Vanco** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Will release with the version 2.1.7 soon.
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                fanhuagang
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    On 03/28/2022 ***@***.***> wrote： 



Hi,
I see that you have made some code changes to fix the issue, thank you so much for that.
But you have not changed the version of the plugin.
Can you please let me know, how to get those code changes to my local Intellij installation?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>
