### ISSUE TITLE
Required plugin com.intellij.modules.java is not installed

### ISSUE THREAD

**Issue by baruchl** [Vanco/SequencePlugin#32]
Hi,
try to load the SequencePlugin, after PyCharm restart, the plugin is not loaded with the following message:
THE PLUGIN WAS NOT LOADED REQUIRED PLUGIN COM.INTELLIJ.MODULES.JAVA IS NOT ENABLED

**Comment by Vanco** [comment]
the SequenceDiagram is ONLY for JAVA. not for other language.

Thanks for your interesting.




    



    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            Vanco Fan
                            
                            
                                
                                    邮箱：fanhuagang@gmail.com
                                
                        
                    
                
            
        
    


Signature is customized by Netease Mail Master


On 11/11/2018 19:17, Busi wrote: Hi,
try to load the SequencePlugin, after PyCharm restart, the plugin is not loaded with the following message:
THE PLUGIN WAS NOT LOADED REQUIRED PLUGIN COM.INTELLIJ.MODULES.JAVA IS NOT ENABLED

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Vanco/SequencePlugin","title":"Vanco/SequencePlugin","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Vanco/SequencePlugin"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Required plugin com.intellij.modules.java is not installed (#32)"}],"action":{"name":"View Issue","url":"https://github.com/Vanco/SequencePlugin/issues/32"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Vanco/SequencePlugin/issues/32",
"url": "https://github.com/Vanco/SequencePlugin/issues/32",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Required plugin com.intellij.modules.java is not installed (#32)",
"sections": [
{
"text": "",
"activityTitle": "**Busi**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@baruchl",
"facts": [
{
"name": "Repository: ",
"value": "Vanco/SequencePlugin"
},
{
"name": "Issue #: ",
"value": 32
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Vanco/SequencePlugin\",\n\"issueId\": 32,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"Vanco/SequencePlugin\",\n\"issueId\": 32\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/Vanco/SequencePlugin/issues/32"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 409058458\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by baruchl** [comment]
Thank you @Vanco
