### ISSUE TITLE
Export text file miss connections

### ISSUE THREAD

**Issue by MassimoDR** [Vanco/SequencePlugin#48]
Hi, I'm using your plugin and it is impressive, but I have a question about the export in text format.
I exported a generated diagram and for each node, there is an entry as the following:

"_classDescription":{ 
"_className":"com.example.PackageDiagramController",
"_attributes":[ 
"public"
]
},
"_methodName":"method1",
"_attributes":[ 
"public"
],
"_argNames":[ 
"params"
],
"_argTypes":[ 
"com.example.InPayload"
],
"_returnType":"java.lang.String",
"_hashCode":-1

It seems to miss the connections among the elements. 
If I'm wrong, please, can you explain to me what am I meant to look at when I need to reconstruct the diagram programmatically?
To be more precise, i was expecting a "reference" to another element where the call happens. For example, in the destination element there can be a property that has the pointer to another element or method. In this case i know where to put the arrow of a call.

Thank you,
Massimo

**Comment by Vanco** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    How to read the exported text file.
        
            
        
    
    
        The 1 line describe the top method you want to generate sequence diagram. the 2 line is describe the method Class 1 called.  the indent is draws as call line (1.1 get). 
        The call is from one line to the direct following line, exact one indent.    In other words, each indent is a call.
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                fanhuagang
                            
                    
                        
                            
                                    fanhuagang@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 1/8/2020 22:27，MassimoDR<notifications@github.com> wrote： 


Hi, I'm using your plugin and it is impressive, but I have a question about the export in text format.
I exported a generated diagram and for each node, there is an entry as the following:
"_classDescription":{
"_className":"com.example.PackageDiagramController",
"_attributes":[
"public"
]
},
"_methodName":"method1",
"_attributes":[
"public"
],
"_argNames":[
"params"
],
"_argTypes":[
"com.example.InPayload"
],
"_returnType":"java.lang.String",
"_hashCode":-1
It seems to miss the connections among the elements.
If I'm wrong, please, can you explain to me what am I meant to look at when I need to reconstruct the diagram programmatically?
To be more precise, i was expecting a "reference" to another element where the call happens. For example, in the destination element there can be a property that has the pointer to another element or method. In this case i know where to put the arrow of a call.
Thank you,
Massimo

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by MassimoDR** [comment]
that's great!
I got why I didn't realize it... I parsed the result in a json formatter that remove the tabulation!

Opening it with a normal editor there is the indentation and it makes a lot of sense now.

thank you a lot.
the issue can be closed.
