### ISSUE TITLE
2020.2 Support

### ISSUE THREAD

**Issue by mikejhill** [Vanco/SequencePlugin#59]
Looks like 2020.2 isn't supported yet. Can this be added?

```
Plugin Error
Plugin "SequenceDiagram" is incompatible (until build 201.SNAPSHOT < IU-202.6397.94).
```

**Comment by Vanco** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    The new version 2.0.2 is published.  it support 202.*Having fun.
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                fanhuagang
                            
                    
                        
                            
                                    fanhuagang@gmail.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 8/6/2020 04:05，Mike Hill<notifications@github.com> wrote： 



Looks like 2020.2 isn't supported yet. Can this be added?
Plugin Error
Plugin "SequenceDiagram" is incompatible (until build 201.SNAPSHOT < IU-202.6397.94).


—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
